import 'package:flutter/material.dart';
import 'main.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [BeritaNasionalAnaTiwi()])),
    );
  }
}

class BeritaNasionalAnaTiwi extends StatelessWidget {
  const BeritaNasionalAnaTiwi({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              width: 390,
              height: 2172,
              clipBehavior: Clip.antiAlias,
              decoration: BoxDecoration(color: Colors.white),
              child: Stack(
                children: [
                  Positioned(
                    left: 20,
                    top: 220,
                    child: Container(
                      width: 349,
                      height: 198,
                      decoration: BoxDecoration(
                        boxShadow: [
                          BoxShadow(
                            color: Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 2),
                            spreadRadius: 0,
                          ),
                        ],
                        image: DecorationImage(
                          image: AssetImage('assets/img/brt/berita4.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 136,
                    child: SizedBox(
                      width: 329,
                      height: 80,
                      child: Text(
                        'Ana/Tiwi akhiri perlawanan ganda AS lewat drama rubber game',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 18,
                          fontFamily: 'Bree Serif',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 500,
                    child: SizedBox(
                      width: 350,
                      child: Text(
                        'Jakarta - Pebulu tangkis ganda putri Indonesia Febriana Dwipuji Kusuma/Amalia Cahaya Pratiwi mengakhiri perlawanan ganda Amerika Serikat Lauren Lam/Allison Lee lewat drama rubber game pada babak 32 besar Jepang Open 2025. \n\nDalam laga yang berlangsung di Tokyo Metropolitan Gymnasium, Tokyo, Rabu malam WIB, Ana/Tiwi susah payah mengatasi Lam/Lee, dengan kemenangan 11-21, 21-14, 21-14. \n\nPada gim pertama, Ana/Tiwi bermain cukup terbuka meladeni gaya yang lebih menunggu dari Lam/Lee. Kedudukan cukup berimbang ketika kedua ganda sama-sama mendulang poin demi poin, 8-8. \n\nSelepas interval, Ana/Tiwi kehilangan konsentrasi dan kerap melakukan kesalahan. Sedangkan Lam/Lee terus mengantongi angka hingga lima poin berturut-turut untuk menutup gim pertama lewat kemenangan 21-11. \n\nPada gim kedua, Ana/Tiwi bermain lebih tenang dan menguasai tempo permainan. Meski demikian Lam/Lee tetap tampil ngotot dan mencoba untuk menguasai tempo. \n\nSkor ketat terus berlanjut hingga memasuki masa interval ketika Ana/Tiwi hanya unggul satu poin, 11-10. Selepas interval, Ana/Tiwi terus mencoba untuk mendikte permainan dan tak memberikan celah untuk Lam/Lee mengembangkan pola. \n\nDi penghujung gim kedua, Ana/Tiwi mengamankan empat poin berturut-turut lantas memaksa rubber game setelah menang lewat skor 21-14. \n\nDi gim penentuan, Ana/Tiwi bermain cukup hati-hati meladeni serangan-serangan dari Lam/Lee. Bermain lebih cerdik membuat Ana/Tiwi mampu unggul lima poin hingga memasuki masa interval, 11-6. \n\nSelepas interval, Ana/Tiwi mampu memanfaatkan setiap kesalahan yang dilakukan Liam/Lee. Servis Lam yang gagal di penghujung gim sekaligus menandai kemenangan Ana/Tiwi lewat skor serupa dengan gim kedua yakni 21-14. \n\nNantinya di babak 16 besar, Ana/Tiwi telah ditunggu oleh ganda Korea Selatan Hye Jeong Kim/Hee Yoo Kong yang sebelumnya mengandaskan perlawanan ganda tuan rumah Jepang Ririna Hiramoto/Haruna Konishi.',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 12,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w300,
                          height: 1.33,
                          letterSpacing: 1.20,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 425,
                    child: SizedBox(
                      width: 350,
                      height: 55,
                      child: Text(
                        'Gambar Pebulu tangkis ganda putri Indonesia Febriana Dwipuji Kusuma (kanan) memberikan kode kepada Amallia Cahaya Pratiwi (kiri) saat bertanding di Indonesia Open 2025 di Istora Senayan, Gelora Bung Karno, Jakarta. (sumber: Antara).',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 10,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w100,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 193,
                    child: SizedBox(
                      width: 157,
                      height: 13,
                      child: Text(
                        '16 Juli 2025 13:19 WIB',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 10,
                          fontFamily: 'AR One Sans',
                          fontWeight: FontWeight.w400,
                          shadows: [
                            Shadow(
                              offset: Offset(0, 4),
                              blurRadius: 5,
                              color: Color(0xFF000000),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 16,
                    top: 1380,
                    child: Text(
                      'Editor: Fofo',
                      textAlign: TextAlign.justify,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'League Spartan',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 17,
                    top: 1407.50,
                    child: Container(
                      width: 351,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF224699),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            strokeAlign: BorderSide.strokeAlignCenter,
                            color: const Color(0xFF224699),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 17,
                    top: 1538,
                    child: Container(
                      width: 351,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF224699),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            strokeAlign: BorderSide.strokeAlignCenter,
                            color: const Color(0xFF224699),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 16,
                    top: 1421,
                    child: Text(
                      'Tags:',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 61,
                    top: 1421,
                    child: SizedBox(
                      width: 76,
                      child: Text(
                        '#KitaBisa',
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 14,
                          fontFamily: 'AR One Sans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 142,
                    top: 1421,
                    child: SizedBox(
                      width: 91,
                      height: 19,
                      child: Text(
                        '#Olahraga',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 14,
                          fontFamily: 'AR One Sans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 61,
                    top: 1446,
                    child: Text(
                      '#DUO',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 273,
                    top: 1421,
                    child: Text(
                      '#Indonesia',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 157,
                    top: 1446,
                    child: Text(
                      '#BuluTangkis',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 22,
                    top: 1496,
                    child: Text(
                      'Bagikan',
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 16,
                        fontFamily: 'League Spartan',
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 152,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/WA ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 107,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/FACEBOOK ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 242,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/IG ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 197,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/X ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),

                  Positioned(
                    left: 28,
                    top: 2027,
                    child: Container(
                      width: 334,
                      height: 135,
                      decoration: ShapeDecoration(
                        shadows: [
                          BoxShadow(
                            color: const Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 4),
                            spreadRadius: 0,
                          ),
                        ],
                        color: Colors.white,
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            color: const Color(0xFF224699),
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 35,
                    top: 2050,
                    child: Container(
                      width: 320,
                      height: 105,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),

                        image: DecorationImage(
                          image: AssetImage('assets/img/iklan1.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 338,
                    top: 2029,
                    child: Container(
                      width: 12,
                      height: 12,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/highlight_off.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 165,
                    top: 2027,
                    child: SizedBox(
                      width: 57.10,
                      height: 13.50,
                      child: Text(
                        'Advertising',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 10,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 18,
                    top: 1566,
                    child: Container(
                      width: 355,
                      height: 416,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF224699),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            color: const Color(0xFF0075CC),
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1777,
                    child: SizedBox(
                      width: 325,
                      height: 20,
                      child: Opacity(
                        opacity: 0.50,
                        child: Text(
                          'Berkomentarlah secara bijaksana dan bertanggung jawab. Komentar sepenuhnya menjadi tanggung jawab komentator seperti diatur dalam UU ',
                          textAlign: TextAlign.justify,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 8,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1842,
                    child: SizedBox(
                      width: 325,
                      height: 20,
                      child: Text(
                        '@Fofo-chn : Jago banget! Indonesia Bisa!!!',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 307,
                    top: 1800,
                    child: Container(
                      width: 51,
                      height: 17,
                      decoration: ShapeDecoration(
                        color: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(4),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 42,
                    top: 1578,
                    child: SizedBox(
                      width: 100,
                      height: 22.65,
                      child: Text(
                        'Beri Komentar',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 307,
                    top: 1801,
                    child: SizedBox(
                      width: 51,
                      height: 15.70,
                      child: Text(
                        'Kirim',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 10,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1610,
                    child: Container(
                      width: 325,
                      height: 158,
                      decoration: ShapeDecoration(
                        color: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 53,
                    top: 1632,
                    child: Opacity(
                      opacity: 0.50,
                      child: Text(
                        'Tulis Tanggapan Anda....',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 12,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1829,
                    child: Container(
                      width: 325,
                      decoration: ShapeDecoration(
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            strokeAlign: BorderSide.strokeAlignCenter,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 64,
                    top: 39,
                    child: Container(
                      width: 262,
                      height: 88,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/Logo-mikirluk.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 347,
                    top: 6,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/batere.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 307,
                    top: 6,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/wifi1.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),

                  Positioned(
                    left: 19,
                    top: 66,
                    child: GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => HomepagePendaftarFix(),
                          ),
                        );
                      },
                      child: Container(
                        width: 30,
                        height: 30,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage('assets/img/back.png'),
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 4,
                    top: 7,
                    child: SizedBox(
                      width: 76,
                      height: 21,
                      child: Text(
                        '04.00',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 20,
                          fontFamily: 'Bree Serif',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
