import 'package:flutter/material.dart';
import 'main.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [BeritaNasionalGayaHidup()])),
    );
  }
}

class BeritaNasionalGayaHidup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              width: 390,
              height: 2172,
              clipBehavior: Clip.antiAlias,
              decoration: BoxDecoration(color: Colors.white),
              child: Stack(
                children: [
                  Positioned(
                    left: 20,
                    top: 260,
                    child: Container(
                      width: 349,
                      height: 198,
                      decoration: BoxDecoration(
                        boxShadow: [
                          BoxShadow(
                            color: Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 2),
                            spreadRadius: 0,
                          ),
                        ],
                        image: DecorationImage(
                          image: AssetImage('assets/img/brt/berita1.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 136,
                    child: SizedBox(
                      width: 329,
                      height: 80,
                      child: Text(
                        'Polisi Indonesia Menahan 12\nTersangka dalam Kasus Perdagangan Bayi',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 18,
                          fontFamily: 'Bree Serif',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 500,
                    child: SizedBox(
                      width: 350,
                      child: Text(
                        'BANDUNG, Indonesia — Pihak berwenang Indonesia telah menahan 12 tersangka setelah mengungkap dugaan sindikat perdagangan bayi yang mengirim lebih dari selusin bayi ke Singapura, ujar seorang pejabat kepolisian kepada AFP pada hari Selasa.\n\nKasus ini terungkap setelah seorang orang tua melaporkan dugaan penculikan bayi kepada polisi, yang kemudian mengarah kepada seorang tersangka yang mengaku telah memperdagangkan 24 bayi, kata Direktur Reserse Kriminal Umum Polda Jawa Barat, Surawan, yang hanya menggunakan satu nama.\n\nPara pelaku diduga memindahkan bayi-bayi tersebut ke Kota Pontianak di Pulau Kalimantan, kemudian mengirim lebih dari selusin dari mereka ke Singapura, ujar pejabat tersebut.\n                     “Berdasarkan dokumen, 14 (bayi) dikirim ke Singapura,” katanya.\n                     “Usia mereka jelas di bawah satu tahun, dengan beberapa berusia tiga bulan, lima bulan, dan enam bulan.”\n\nPihak berwenang berhasil menyelamatkan lima bayi di Pontianak dan satu bayi di Tangerang, sebuah kota dekat ibu kota Indonesia, Jakarta. Mereka juga menangkap 12 tersangka di Jakarta, Pontianak, dan Kota Bandung di Pulau Jawa.\n                     “Mereka ini sindikat, sindikat perdagangan bayi. Masing-masing memiliki peran,” ujar Surawan.\n\nBeberapa tersangka diduga bertugas mencari bayi-bayi tersebut, sementara yang lain merawat mereka, menampung mereka, atau menyiapkan dokumen administrasi sipil, seperti kartu keluarga dan paspor.\n                     Sindikat ini telah beroperasi sejak tahun 2023, kata Surawan berdasarkan keterangan para tersangka.\n\nPolisi mengatakan mereka menargetkan “orang tua atau ibu yang menolak merawat anak mereka” dengan imbalan uang.\n\nSurawan menyatakan bahwa orang tua yang melaporkan penculikan tersebut “sebenarnya sudah memiliki kesepakatan” dengan para penyelundup sebelum kelahiran anaknya, tetapi melapor kepada polisi karena tidak menerima pembayaran seperti yang dijanjikan.',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 12,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w300,
                          height: 1.33,
                          letterSpacing: 1.20,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 465,
                    child: SizedBox(
                      width: 350,
                      height: 17,
                      child: Text(
                        'Gambar ilustrasi penculik dan anak (sumber: sendiri).',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 10,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w100,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 20,
                    top: 223,
                    child: SizedBox(
                      width: 157,
                      height: 13,
                      child: Text(
                        '16 Juli 2025 09:19 WIB',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 10,
                          fontFamily: 'AR One Sans',
                          fontWeight: FontWeight.w400,
                          shadows: [
                            Shadow(
                              offset: Offset(0, 4),
                              blurRadius: 5,
                              color: Color(0xFF000000).withOpacity(0.25),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 16,
                    top: 1365,
                    child: Text(
                      'Editor: Fofo',
                      textAlign: TextAlign.justify,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'League Spartan',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 17,
                    top: 1407.50,
                    child: Container(
                      width: 351,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF224699),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            strokeAlign: BorderSide.strokeAlignCenter,
                            color: const Color(0xFF224699),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 17,
                    top: 1538,
                    child: Container(
                      width: 351,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF224699),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            strokeAlign: BorderSide.strokeAlignCenter,
                            color: const Color(0xFF224699),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 16,
                    top: 1421,
                    child: Text(
                      'Tags:',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                        shadows: [
                          Shadow(
                            offset: Offset(0, 4),
                            blurRadius: 4,
                            color: Color(0xFF000000).withOpacity(0.25),
                          ),
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 61,
                    top: 1421,
                    child: SizedBox(
                      width: 76,
                      child: Text(
                        '#Polisi',
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 14,
                          fontFamily: 'AR One Sans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 152,
                    top: 1421,
                    child: SizedBox(
                      width: 91,
                      height: 19,
                      child: Text(
                        '#GayaHidup',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 14,
                          fontFamily: 'AR One Sans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 61,
                    top: 1446,
                    child: Text(
                      '#Indonesia',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 273,
                    top: 1421,
                    child: Text(
                      '#Penjahat',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 157,
                    top: 1446,
                    child: Text(
                      '#Bayi',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 14,
                        fontFamily: 'AR One Sans',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 22,
                    top: 1496,
                    child: Text(
                      'Bagikan',
                      style: TextStyle(
                        color: const Color(0xFF224699),
                        fontSize: 16,
                        fontFamily: 'League Spartan',
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 152,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/WA ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 107,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/FACEBOOK ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 242,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/IG ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 197,
                    top: 1492,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/X ICON.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),

                  Positioned(
                    left: 28,
                    top: 2027,
                    child: Container(
                      width: 334,
                      height: 135,
                      decoration: ShapeDecoration(
                        shadows: [
                          BoxShadow(
                            color: const Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 4),
                            spreadRadius: 0,
                          ),
                        ],
                        color: Colors.white,
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            color: const Color(0xFF224699),
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 35,
                    top: 2050,
                    child: Container(
                      width: 320,
                      height: 105,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),

                        image: DecorationImage(
                          image: AssetImage('assets/img/iklan2.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 338,
                    top: 2029,
                    child: Container(
                      width: 12,
                      height: 12,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/highlight_off.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 165,
                    top: 2027,
                    child: SizedBox(
                      width: 57.10,
                      height: 13.50,
                      child: Text(
                        'Advertising',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 10,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 18,
                    top: 1566,
                    child: Container(
                      width: 355,
                      height: 416,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF224699),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            color: const Color(0xFF0075CC),
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1777,
                    child: SizedBox(
                      width: 325,
                      height: 20,
                      child: Opacity(
                        opacity: 0.50,
                        child: Text(
                          'Berkomentarlah secara bijaksana dan bertanggung jawab. Komentar sepenuhnya menjadi tanggung jawab komentator seperti diatur dalam UU ',
                          textAlign: TextAlign.justify,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 8,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1842,
                    child: SizedBox(
                      width: 325,
                      height: 20,
                      child: Text(
                        'Belum ada komentar. Jadilah yang pertama untuk memberikan komentar!',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 307,
                    top: 1800,
                    child: Container(
                      width: 51,
                      height: 17,
                      decoration: ShapeDecoration(
                        color: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(4),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 42,
                    top: 1578,
                    child: SizedBox(
                      width: 100,
                      height: 22.65,
                      child: Text(
                        'Beri Komentar',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 307,
                    top: 1801,
                    child: SizedBox(
                      width: 51,
                      height: 15.70,
                      child: Text(
                        'Kirim',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFF224699),
                          fontSize: 10,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1610,
                    child: Container(
                      width: 325,
                      height: 158,
                      decoration: ShapeDecoration(
                        color: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 53,
                    top: 1632,
                    child: Opacity(
                      opacity: 0.50,
                      child: Text(
                        'Tulis Tanggapan Anda....',
                        textAlign: TextAlign.justify,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 12,
                          fontFamily: 'League Spartan',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 33,
                    top: 1829,
                    child: Container(
                      width: 325,
                      decoration: ShapeDecoration(
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            width: 1,
                            strokeAlign: BorderSide.strokeAlignCenter,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 64,
                    top: 39,
                    child: Container(
                      width: 262,
                      height: 88,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/Logo-mikirluk.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 347,
                    top: 6,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/batere.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 307,
                    top: 6,
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('assets/img/wifi1.png'),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                  ),

                  Positioned(
                    left: 19,
                    top: 66,
                    child: GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => HomepagePendaftarFix(),
                          ),
                        );
                      },
                      child: Container(
                        width: 30,
                        height: 30,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage('assets/img/back.png'),
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 4,
                    top: 7,
                    child: SizedBox(
                      width: 76,
                      height: 21,
                      child: Text(
                        '04.00',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 20,
                          fontFamily: 'Bree Serif',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
