import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [SignInPage()])),
    );
  }
}

class SignInPage extends StatelessWidget {
  const SignInPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 42,
                top: 478,
                child: SizedBox(
                  width: 308.90,
                  height: 25.30,
                  child: Opacity(
                    opacity: 0.50,
                    child: Text(
                      'atau ',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Fredoka',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 275.75,
                child: Container(
                  width: 308.90,
                  height: 43.52,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF224699),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 67.61,
                top: 284.86,
                child: SizedBox(
                  width: 98.16,
                  height: 26.32,
                  child: Text(
                    'Password',
                    style: TextStyle(
                      color: const Color(0x7F224699),
                      fontSize: 16,
                      fontFamily: 'League Spartan',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 338.51,
                child: Container(
                  width: 308.90,
                  height: 43.52,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF224699),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 146.37,
                top: 347.62,
                child: SizedBox(
                  width: 98.16,
                  height: 26.32,
                  child: Text(
                    'Sign In',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF224699),
                      fontSize: 16,
                      fontFamily: 'League Spartan',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46.50,
                top: 494.19,
                child: Opacity(
                  opacity: 0.50,
                  child: Container(
                    width: 132.38,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 513.43,
                child: Container(
                  width: 308.90,
                  height: 43.52,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF224699),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111.34,
                top: 524.56,
                child: SizedBox(
                  width: 171.11,
                  height: 25.30,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Masuk dengan',
                          style: TextStyle(
                            color: const Color(0xFF224699),
                            fontSize: 16,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        TextSpan(
                          text: ' Google',
                          style: TextStyle(
                            color: const Color(0xFF224699),
                            fontSize: 16,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 618.69,
                child: Container(
                  width: 308.90,
                  height: 43.52,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF224699),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111.34,
                top: 627.80,
                child: SizedBox(
                  width: 171.11,
                  height: 26.32,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Masuk dengan',
                          style: TextStyle(
                            color: const Color(0xFF224699),
                            fontSize: 16,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        TextSpan(
                          text: ' Apple',
                          style: TextStyle(
                            color: const Color(0xFF224699),
                            fontSize: 16,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 567.07,
                child: Container(
                  width: 308.90,
                  height: 43.52,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF224699),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111.34,
                top: 573.14,
                child: SizedBox(
                  width: 171.11,
                  height: 26.32,
                  child: Text(
                    'Masuk dengan Facebook',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Fredoka',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111.34,
                top: 576.18,
                child: SizedBox(
                  width: 171.11,
                  height: 26.32,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Masuk dengan',
                          style: TextStyle(
                            color: const Color(0xFF224699),
                            fontSize: 16,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        TextSpan(
                          text: ' Facebook',
                          style: TextStyle(
                            color: const Color(0xFF224699),
                            fontSize: 16,
                            fontFamily: 'League Spartan',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 393,
                child: Text(
                  'Lupa password?',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF224699),
                    fontSize: 16,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w400,
                    height: 1,
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 162,
                child: Text(
                  'Selamat Datang!',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF224699),
                    fontSize: 20,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w500,
                    height: 1,
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 162,
                child: Text(
                  'Selamat Datang!',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF224699),
                    fontSize: 20,
                    fontFamily: 'League Spartan',
                    fontWeight: FontWeight.w500,
                    height: 1,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 213,
                child: Container(
                  width: 308.90,
                  height: 42.51,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF224699),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 70,
                top: 222,
                child: SizedBox(
                  width: 98.16,
                  height: 26.32,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0x7F224699),
                      fontSize: 16,
                      fontFamily: 'League Spartan',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
